### ISSUE TITLE
Share your Dataset and Training Code

### ISSUE THREAD

**Issue by cuongnguyengit** [minuva/llm-flow-classification#2]
Hello, this is an interesting project. Can you please share the source code and training data of the project? If possible, a little more guidance would be great

**Comment by pvl** [comment]
Thank you @cuongnguyengit  for your interest in our project! Currently, the training dataset isn't public, but we'll definitely consider this request when we start working on the next release.

**Comment by pvl** [comment]
To be evaluated for next release.

**Comment by cuongnguyengit** [comment]
See that soon, thank you
